# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Not requested', 'Not requested'), ('Rejected', 'Rejected')], default='Rejected', max_length=120)),
                ('region', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=12)),
                ('social_media', models.CharField(max_length=12)),
                ('last_online', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Our representatives',
            },
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('suggestion', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Representative suggestions',
            },
        ),
    ]
