# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='user',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
