# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20171221_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='position_type',
            field=models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=120, null=True),
        ),
    ]
