# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedpurchases',
            name='lastdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
