# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_returnedpurchases_lastdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='buyers_acc',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
