# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_purchases_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='currency',
            field=models.CharField(choices=[('$', '$'), ('BTC', 'BTC')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='paidproducts',
            name='currency',
            field=models.CharField(choices=[('$', '$'), ('BTC', 'BTC')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.CharField(choices=[('$', '$'), ('BTC', 'BTC')], default='$', max_length=5),
        ),
    ]
