# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20171203_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepurchase',
            name='processor',
            field=models.CharField(choices=[('Account balance', 'Account balance'), ('Perfectmoney', 'Perfectmoney'), ('Payeer', 'Payeer'), ('Bitcoin', 'Bitcoin')], default='Not received', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='processor',
            field=models.CharField(choices=[('Account balance', 'Account balance'), ('Perfectmoney', 'Perfectmoney'), ('Payeer', 'Payeer'), ('Bitcoin', 'Bitcoin')], default='Not received', max_length=128),
        ),
    ]
