# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20171221_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidproducts',
            name='AdsPackage',
            field=models.CharField(blank=True, choices=[('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('1 Month', '1 Month'), ('1 Month 2 Weeks', '1 Month 2 Weeks'), ('2 Months', '2 Months'), ('2 Month 2 Weeks', '2 Month 2 Weeks'), ('3 Months', '3 Months'), ('3 Month 2 Weeks', '3 Month 2 Weeks'), ('Month4', '4 Months'), ('3 Month 2 Weeks', '3 Month 2 Weeks')], max_length=125, null=True),
        ),
    ]
