# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_paidproducts_adspackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidproducts',
            name='Price',
            field=models.PositiveIntegerField(default='', max_length=12),
        ),
    ]
