# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20171222_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidproducts',
            name='Price',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
