# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20171226_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Price',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='Price_sold',
            field=models.FloatField(null=True),
        ),
    ]
