# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20171226_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='currency_used',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
