# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_products_currency_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='album',
        ),
    ]
