# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_remove_products_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', '$'), ('BTC', 'BTC')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='currency_used',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
