# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transactionpayeer_actualdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionperfectmoney',
            name='actualDeposit',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transactionperfectmoney',
            name='hashid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transactionperfectmoney',
            name='sign',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Unconfirmed', 'Unconfirmed')], default='Unconfirmed', max_length=120),
        ),
    ]
