# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171219_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionperfectmoney',
            name='title',
        ),
    ]
