# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171220_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceredeposit',
            name='title',
        ),
    ]
