# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_balanceredeposit_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceredeposit',
            name='expectedIncome',
            field=models.FloatField(default=0),
        ),
    ]
