# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_balanceredeposit_expectedincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpayeer',
            name='expectedIncome',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transactionperfectmoney',
            name='expectedIncome',
            field=models.FloatField(default=0),
        ),
    ]
