# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171220_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositsverified',
            old_name='account_number',
            new_name='amount_deposited',
        ),
        migrations.RenameField(
            model_name='depositsverified',
            old_name='name',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='depositsverified',
            old_name='kumbukumbu_no',
            new_name='hashid',
        ),
        migrations.RenameField(
            model_name='depositsverified',
            old_name='verification_code',
            new_name='processor',
        ),
        migrations.RemoveField(
            model_name='depositsverified',
            name='depositing_amount',
        ),
        migrations.RemoveField(
            model_name='depositsverified',
            name='depositing_id',
        ),
        migrations.RemoveField(
            model_name='depositsverified',
            name='status',
        ),
        migrations.RemoveField(
            model_name='depositsverified',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='depositsverified',
            name='expected_income',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositsverified',
            name='plan',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='depositsverified',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='depositsverified',
            name='sign',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='depositsverified',
            name='startdate',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='depositsverified',
            name='username',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
