# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171221_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositsverified',
            old_name='plan',
            new_name='package',
        ),
    ]
