# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171221_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositsverified',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='depositsverified',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
    ]
