# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_processors_xamcoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processors',
            name='XamCoin',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
