# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20171221_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processors',
            name='Etherium',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='processors',
            name='adcash',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='processors',
            name='bitcoin',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='processors',
            name='payeer',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='processors',
            name='perfectmoney',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
