# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20171221_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedWithdrawals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120, null=True)),
                ('full_name', models.CharField(max_length=120, null=True)),
                ('balance', models.CharField(max_length=120, null=True)),
                ('processor', models.CharField(max_length=120, null=True)),
                ('processor_account_number', models.CharField(blank=True, max_length=120, null=True)),
                ('m_amount', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=120, null=True)),
                ('Status', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='last_withdrawal',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
