# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20171222_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='last_withdrawal',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
