# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20171222_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='withdrawing_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
