# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20171222_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawprocessor',
            name='m_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
