# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20171222_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawprocessor',
            name='email',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
