# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20171223_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionbitcoin',
            name='actualDeposit',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='transactionbitcoin',
            name='b_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
