# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20171223_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvCashBalanceDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=125, null=True)),
                ('username', models.CharField(max_length=125, null=True)),
                ('processor', models.CharField(max_length=125, null=True)),
                ('a_amount', models.FloatField(default=0, null=True)),
                ('actualDeposit', models.CharField(default=0, max_length=120)),
                ('sign', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Unconfirmed', 'Unconfirmed')], default='Unconfirmed', max_length=120)),
                ('hashid', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='bitcoinBalanceDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=125, null=True)),
                ('username', models.CharField(max_length=125, null=True)),
                ('processor', models.CharField(max_length=125, null=True)),
                ('b_amount', models.FloatField(default=0, null=True)),
                ('actualDeposit', models.CharField(default=0, max_length=120)),
                ('sign', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Unconfirmed', 'Unconfirmed')], default='Unconfirmed', max_length=120)),
                ('hashid', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OKPayBalanceDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=125, null=True)),
                ('username', models.CharField(max_length=125, null=True)),
                ('processor', models.CharField(max_length=125, null=True)),
                ('o_amount', models.FloatField(default=0, null=True)),
                ('actualDeposit', models.CharField(default=0, max_length=120)),
                ('sign', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Unconfirmed', 'Unconfirmed')], default='Unconfirmed', max_length=120)),
                ('hashid', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayeerBalanceDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=125, null=True)),
                ('username', models.CharField(max_length=125, null=True)),
                ('processor', models.CharField(max_length=125, null=True)),
                ('m_amount', models.FloatField(default=0, null=True)),
                ('actualDeposit', models.CharField(default=0, max_length=120)),
                ('sign', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Unconfirmed', 'Unconfirmed')], default='Unconfirmed', max_length=120)),
                ('hashid', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfectMoneyrBalanceDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=125, null=True)),
                ('username', models.CharField(max_length=125, null=True)),
                ('processor', models.CharField(max_length=125, null=True)),
                ('p_amount', models.FloatField(default=0, null=True)),
                ('actualDeposit', models.CharField(default=0, max_length=120)),
                ('sign', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Unconfirmed', 'Unconfirmed')], default='Unconfirmed', max_length=120)),
                ('hashid', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
