# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_advcashdeposit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advcashdeposit',
            options={'verbose_name_plural': 'adv Deposit table'},
        ),
    ]
