# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_investment_bitcoin_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='account_type',
            field=models.CharField(choices=[('Usd', 'Usd'), ('Bitcoin', 'Bitcoin')], default='', max_length=20),
        ),
    ]
