# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20171224_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bitcoin_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
