# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 08:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_bitcoinredepositmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinWithdrawModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120, null=True)),
                ('full_name', models.CharField(max_length=120, null=True)),
                ('balance', models.CharField(max_length=120, null=True)),
                ('processor', models.CharField(max_length=120, null=True)),
                ('processor_acc_number', models.CharField(max_length=120, null=True)),
                ('b_amount', models.PositiveIntegerField(null=True)),
                ('account_number', models.CharField(max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bitcoinredepositmodels',
            options={'verbose_name_plural': 'Bitcoin Redeposit transaction'},
        ),
        migrations.AlterField(
            model_name='advcashbalancedeposit',
            name='a_amount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='advcashdeposit',
            name='a_amount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='balanceredeposit',
            name='amount_transfered',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bitcoinbalancedeposit',
            name='b_amount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bitcoinredepositmodels',
            name='b_amount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='depositsverified',
            name='amount_deposited',
            field=models.CharField(max_length=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='Bitcoin_balance',
            field=models.FloatField(blank=True, default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='requested_amount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='okpaybalancedeposit',
            name='o_amount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='okpaydeoisitmodel',
            name='o_amount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payeerbalancedeposit',
            name='m_amount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='perfectmoneyrbalancedeposit',
            name='p_amount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transactionbitcoin',
            name='b_amount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transactionpayeer',
            name='m_amount',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transactionperfectmoney',
            name='PAYMENT_AMOUNT',
            field=models.FloatField(max_length=35, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='amount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bitcoin_amount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
