# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_userinfo_total_bitcoin_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransaction',
            name='currency_transfered',
            field=models.CharField(choices=[('Usd', 'Usd'), ('Bitcoin', 'Bitcoin')], max_length=120, null=True),
        ),
    ]
