# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 19:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20171227_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processors',
            name='Etherium',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processors',
            name='XamCoin',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processors',
            name='adcash',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processors',
            name='bitcoin',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processors',
            name='okpay',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processors',
            name='payeer',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='processors',
            name='perfectmoney',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
