# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20171229_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpayeer',
            name='description',
            field=models.CharField(max_length=185, null=True),
        ),
        migrations.AddField(
            model_name='transactionpayeer',
            name='m_curr',
            field=models.CharField(max_length=185, null=True),
        ),
        migrations.AddField(
            model_name='transactionpayeer',
            name='m_desc',
            field=models.CharField(max_length=185, null=True),
        ),
        migrations.AddField(
            model_name='transactionpayeer',
            name='m_key',
            field=models.CharField(max_length=185, null=True),
        ),
        migrations.AddField(
            model_name='transactionpayeer',
            name='m_orderid',
            field=models.CharField(max_length=185, null=True),
        ),
        migrations.AddField(
            model_name='transactionpayeer',
            name='m_shop',
            field=models.CharField(max_length=185, null=True),
        ),
        migrations.AddField(
            model_name='transactionpayeer',
            name='m_sign',
            field=models.CharField(max_length=185, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpayeer',
            name='actualDeposit',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
