# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptoseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('balance_amount', models.CharField(blank=True, max_length=120, null=True)),
                ('exchanger', models.CharField(max_length=120, null=True)),
                ('Give', models.CharField(max_length=120, null=True)),
                ('Get', models.CharField(max_length=120, null=True)),
                ('Reserve', models.CharField(max_length=120, null=True)),
                ('Reviews', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
