# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoreseller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoseller',
            name='currency',
            field=models.CharField(choices=[('Dollar', 'USD'), ('Bitcoin', 'Bitcoin')], max_length=120, null=True),
        ),
    ]
