# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-12 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoreseller', '0002_cryptoseller_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoseller',
            name='Receiving_processor',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
