# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-14 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoreseller', '0003_cryptoseller_receiving_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoseller',
            name='currency',
            field=models.CharField(choices=[('USD Wallet', 'USD Wallet'), ('Bitcoin Wallet', 'Bitcoin Wallet')], max_length=120, null=True),
        ),
    ]
