# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoreseller', '0004_auto_20180414_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoseller',
            name='Receiving_processor',
        ),
        migrations.AddField(
            model_name='cryptoseller',
            name='Payment_method',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
